---
# Source: prometheus/charts/alertmanager/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-community-alertmanager
  labels:
    helm.sh/chart: alertmanager-1.29.0
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/version: "v0.29.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
spec:
  type: ClusterIP
  ports:
    - port: 9093
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: prometheus-community
---
# Source: prometheus/charts/alertmanager/templates/services.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus-community-alertmanager-headless
  labels:
    helm.sh/chart: alertmanager-1.29.0
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/version: "v0.29.0"
    app.kubernetes.io/managed-by: Helm
  namespace: default
spec:
  clusterIP: None
  ports:
    - port: 9093
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/instance: prometheus-community
