apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alloy-gateway-ingressroute
  namespace: alloy-gateway
spec:
  entryPoints: []
    # If not specified, HTTP routers will accept requests from all EntryPoints in the list of default EntryPoints.
    # - web
    # - websecure
  routes:
    - match: Host(`alloy-gateway.poddle.uz`)
      kind: Rule
      services:
        - name: alloy-gateway
          port: 12345
  # tls:
  #   secretName: wildcard-poddle-uz-tls-secret
