apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: alloy-gateway-otlp-ingressroutetcp
  namespace: alloy-gateway
spec:
  entryPoints:
    - tcp
  routes:
    - match: HostSNI(`alloy-gateway.poddle.uz`)
      services:
        - name: alloy-gateway
          port: 4317
  # tls:
  #   secretName: wildcard-poddle-uz-tls-secret
