apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: alloy-gateway-otlp-http
  namespace: alloy-gateway
spec:
  parentRefs:
    - name: traefik
      namespace: traefik
      kind: Gateway
      sectionName: otlp-http

  hostnames:
    - alloy-gateway.poddle.uz

  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /v1/traces
        - path:
            type: PathPrefix
            value: /v1/metrics
        - path:
            type: PathPrefix
            value: /v1/logs

      backendRefs:
        - name: alloy-gateway
          namespace: alloy-gateway
          port: 4318
