# yaml-language-server: $schema=values.schema.json

server:
  enabled: true

  extraFlags:
    - web.enable-lifecycle
    - storage.tsdb.wal-compression
    - storage.tsdb.no-lockfile

  global:
    scrape_interval: 15s
    scrape_timeout: 10s
    evaluation_interval: 1m

  extraArgs:
    # Helm takes null to indicate that a key needs to be removed
    # https://helm.sh/docs/chart_template_guide/values_files/#deleting-a-default-key
    web.enable-remote-write-receiver: ""

  persistentVolume:
    enabled: true
    size: 10Gi
    storageClass: local-path

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  retention: "30d"

scrapeConfigs:
  prometheus:
    enabled: false
  kubernetes-api-servers:
    enabled: false
  kubernetes-nodes:
    enabled: false
  kubernetes-nodes-cadvisor:
    enabled: false
  kubernetes-service-endpoints:
    enabled: false
  kubernetes-service-endpoints-slow:
    enabled: false
  prometheus-pushgateway:
    enabled: false
  kubernetes-services:
    enabled: false
  kubernetes-pods:
    enabled: false
  kubernetes-pods-slow:
    enabled: false

serverFiles:
  prometheus.yml:
    scrape_configs: []

alertmanager:
  enabled: false

prometheus-pushgateway:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false
