---
# Source: prometheus/templates/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/version: v3.7.3
    helm.sh/chart: prometheus-27.46.0
    app.kubernetes.io/part-of: prometheus
  name: prometheus-community-server
subjects:
  - kind: ServiceAccount
    name: prometheus-community-server
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-community-server
