---
# Source: prometheus/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/version: v3.7.3
    helm.sh/chart: prometheus-27.46.0
    app.kubernetes.io/part-of: prometheus
  name: prometheus-community-server
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "8Gi"
