---
# Source: prometheus/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/version: v3.7.3
    helm.sh/chart: prometheus-27.46.0
    app.kubernetes.io/part-of: prometheus
  name: prometheus-community-server
  namespace: default
  annotations:
    {}
