---
# Source: prometheus/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-community
    app.kubernetes.io/version: v3.7.3
    helm.sh/chart: prometheus-27.46.0
    app.kubernetes.io/part-of: prometheus
  name: prometheus-community-server
  namespace: default
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: prometheus-community
  sessionAffinity: None
  type: "ClusterIP"
