[package]
name = "users-core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
jsonwebtoken.workspace = true
chrono.workspace = true
serde.workspace = true
uuid.workspace = true
