apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-staging-i
spec:
  acme:
    email: atajanovkamronbek2003@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-key
    solvers:
      - http01:
          ingress:
            serviceType: ClusterIP
            ingressClassName: traefik
