apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
# Metallb address pool
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool
  namespace: metallb-system
spec:
  addresses:
    # make sure the DHCP server won't use that range
    - 192.168.31.10-192.168.31.19
---
# L2 configuration
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-adver-tisement
  namespace: metallb-system
spec:
  ipAddressPools:
    - ip-address-pool
