apiVersion: traefik.io/v1alpha1
kind: TLSStore
metadata:
  name: default
  namespace: traefik
spec:
  certificates:
    - secretName: wildcard-poddle-uz-tls
  # defaultGeneratedCert:
  #   resolver: vault-k8s-ci
  #   domain:
  #     main: poddle.uz
  #     sans:
  #       - \*.poddle.uz
