apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: vault-transport
  namespace: vault
spec:
  serverName: vault-active
  insecureSkipVerify: false
  rootCAs:
    - secret: vault-root-ca-bundle
  # This is for mTLS
  # certificatesSecrets:
  #   - vault-root-ca-bundle
