# yaml-language-server: $schema=values.schema.json

ipam:
  mode: kubernetes
# This IP must match vm IP
k8sServiceHost: 10.212.0.7
k8sServicePort: 6443
kubeProxyReplacement: true

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 768Mi
