apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: poddle-system
spec:
  type: ClusterIP
  selector:
    service: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: poddle-system
spec:
  type: ClusterIP
  selector:
    service: users-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: billing-api
  namespace: poddle-system
spec:
  type: ClusterIP
  selector:
    service: billing-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: compute-api
  namespace: poddle-system
spec:
  type: ClusterIP
  selector:
    service: compute-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: compute-provisioner
  namespace: poddle-system
spec:
  type: ClusterIP
  selector:
    service: compute-provisioner
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: compute-metrics-worker
  namespace: poddle-system
spec:
  type: ClusterIP
  selector:
    service: compute-metrics-worker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: compute-reconciler
  namespace: poddle-system
spec:
  type: ClusterIP
  selector:
    service: compute-reconciler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
