defaultVaultConnection:
  enabled: true

  address: "https://vault-active.vault.svc:8200"
  caCertSecret: "vault-root-ca-bundle"
  skipTLSVerify: false

telemetry:
  serviceMonitor:
    enabled: false
