global:
  enabled: true
  tlsDisable: false

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m

injector:
  enabled: false

server:
  # Mount TLS certificates
  extraEnvironmentVars:
    # GOOGLE_REGION: global
    # GOOGLE_PROJECT: my-poddle-project
    # GOOGLE_CREDENTIALS: /vault/userconfig/poddle-kms-service-account.json
    # VAULT_GCPCKMS_SEAL_KEY_RING: vault-unseal-key-ring
    # VAULT_GCPCKMS_SEAL_CRYPTO_KEY: vault-unseal-crypto-key
    VAULT_CACERT: /vault/userconfig/ca.crt
    VAULT_TLSCERT: /vault/userconfig/tls.crt
    VAULT_TLSKEY: /vault/userconfig/tls.key

  volumes:
    - name: vault-server-tls-secret-volume
      secret:
        defaultMode: 420
        secretName: vault-server-tls-secret
    # - name: poddle-kms-service-account-volume
    #   secret:
    #     defaultMode: 420
    #     secretName: poddle-kms-service-account-secret

  volumeMounts:
    - mountPath: /vault/userconfig
      name: vault-server-tls-secret-volume
      readOnly: true
    # - mountPath: /vault/userconfig
    #   name: poddle-kms-service-account-volume
    #   readOnly: true

  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 256Mi
      cpu: 250m

  # Health checks adjusted for TLS
  # For HA configuration and because we need to manually init the vault,
  # we need to define custom readiness/liveness Probe settings
  readinessProbe:
    enabled: true
    scheme: HTTPS
    path: "/v1/sys/health?standbyok=true&sealedcode=204&uninitcode=204"
  livenessProbe:
    enabled: true
    scheme: HTTPS
    path: "/v1/sys/health?standbyok=true"
    initialDelaySeconds: 60

  # Affinity to spread across nodes
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              app.kubernetes.io/name: {{ template "vault.name" . }}
              app.kubernetes.io/instance: "{{ .Release.Name }}"
              component: server
          topologyKey: kubernetes.io/hostname

  ha:
    enabled: true
    replicas: 3

    raft:
      enabled: true
      setNodeId: true

      config: |
        ui = true

        cluster_name = "vault-integrated-storage"

        listener "tcp" {
          tls_disable = 0
          address = "[::]:8200"
          cluster_address = "[::]:8201"
          tls_cert_file = "/vault/tls/tls.crt"
          tls_key_file = "/vault/tls/tls.key"
          tls_client_ca_file = "/vault/tls/ca.crt"
        }

        seal "gcpckms" {
          disabled    = "true"
          # region      = "global"
          # project     = "Poddle-Dev"
          # credentials = "/vault/userconfig/poddle-kms-service-account.json"
          # key_ring    = "vault-unseal-key-ring"
          # crypto_key  = "vault-unseal-crypto-key"
        }

        storage "raft" {
          path = "/vault/data"
          
          retry_join {
            leader_api_addr = "https://vault-0.vault-internal:8200"
            leader_tls_servername = "vault" # Matches the CommonName in your cert
            leader_ca_cert_file = "/vault/tls/ca.crt"
            leader_client_cert_file = "/vault/tls/tls.crt"
            leader_client_key_file = "/vault/tls/tls.key"
          }
          
          retry_join {
            leader_api_addr = "https://vault-1.vault-internal:8200"
            leader_tls_servername = "vault" # Matches the CommonName in your cert
            leader_ca_cert_file = "/vault/tls/ca.crt"
            leader_client_cert_file = "/vault/tls/tls.crt"
            leader_client_key_file = "/vault/tls/tls.key"
          }
          
          retry_join {
            leader_api_addr = "https://vault-2.vault-internal:8200"
            leader_tls_servername = "vault" # Matches the CommonName in your cert
            leader_ca_cert_file = "/vault/tls/ca.crt"
            leader_client_cert_file = "/vault/tls/tls.crt"
            leader_client_key_file = "/vault/tls/tls.key"
          }
        }

        service_registration "kubernetes" {}

  dataStorage:
    size: 10Gi
    mountPath: "/vault/data"
    storageClass: local-path # Change to longhorn/rook-ceph for production

  auditStorage:
    enabled: true
    size: 5Gi
    mountPath: "/vault/audit"
    storageClass: local-path

ui:
  enabled: true
  serviceType: ClusterIP
